# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - colon
  - comma
  - control_statement
  - nesting
  - cyclomatic_complexity
  - trailing_comma
  - opening_brace
  - void_function_in_ternary
  - multiple_closures_with_trailing_closure
  - closure_parameter_position # we need this off so we can separate closure params into new lines so the line length doesn't become extreme. `.run { [closure_param_one = state.xyz, closure_param_two = state.abc] }` closures frequently need multiple args because they need to alias properties from the `inout State`.
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`

# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace
included: # paths to include during linting. `--path` is ignored if present.
  - iCats

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 60
    error: 70
  excluded:
    - iPhone
    - ID
  allowed_symbols: ["_", "`"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  max_length: # only max_length
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - GlobalAPIKey
    - Current
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
# custom rules
